### ISSUE TITLE
IdP metadata from local file

### ISSUE THREAD

**Issue by aledeganopix4d** [itzg/saml-auth-proxy#7]
First of all hello and thank you for this very interesting project!

I am trying to configure `saml-auth-proxy` with Jumpcloud.
Unfortunately it would seem that Jumpcloud does not expose a public URL where to fetch the XML.

However, after authentication, the metadata XML can be downloaded. Thus if `saml-auth-proxy` could open the metadata XML as a file this issue could be easily solved.

I might be able to contribute the feature myself if there's interest.

NOTE: to verify that the file loading was indeed the only blocker to implement Jumpcloud, I've served the file from a local web host and it works as expected.

**Comment by itzg** [comment]
That seems to be a very helpful enhancement since I imagine there are some catch-22 cases where the endpoint is not available until the IdP is configured with the metadata.

I would be very appreciative of a PR, but also don't mind addressing myself, if needed. I'm wondering if we should provide a couple of options:
- write metadata to file on startup
- output metadata to stdout

The latter might be more useful for kubernetes style deployments where the cert/keys can be mounted read-only and there wouldn't be a need for a writable volume to be attached.

**Comment by aledeganopix4d** [comment]
Hey @itzg thanks for the quick reply.
I don't fully understand your comment, perhaps I worded my proposition poorly.

I was talking about the metadata that comes from the IdP which normally would be loaded with the option `-idp-metadata-url` and so having an analogous option, e.g. `-idp-metadata-path` to load it from file instead.

In my use case I am not using the metadata which `saml-auth-proxy` outputs, as I configure the app in Jumpcloud "a priori".

**Comment by itzg** [comment]
Yes, I misunderstood the ask and was thinking of the SP metadata even though you clearly stated IdP :). The PR totally helped to get me in the right gear.
